# (PART\*) Dominando la reactividad {.unnumbered}

# Introducción {#reactivity-intro .unnumbered}

Ya tienes a tu haber una serie de técnicas prácticas que te permiten crear una amplia gama de aplicaciones útiles.

A continuación enfocaremos nuestra atención a la teoría de la reactividad que subyace a la magia de Shiny:

-   En el capítulo \@ref(reactive-motivation) aprenderás por qué el modelo de programación reactiva es necesario y un poco acerca de la historia de la programación reactiva fuera de R. 

-   En el capítulo \@ref(reactive-graph), aprenderás sobre todos los detalles de un gráfico reactivo que determinan cuándo exactamente los componentes reactivos se actualizan. 

-   En el capítulo \@ref(reactivity-objects), aprenderás sobre los bloques de construcción subyacentes, particularmente acerca de observadores (_observers_) e invalidaciones cronometradas (_timed invalidations_).

-   En el capítulo \@ref(reactivity-components), aprenderás sobre cómo escapar de las constricciones del gráfico reactivo usando  `reactiveVal()` y `observe()`.

Ciertamente, no es necesario entender todos estos detalles para el desarrollo rutinario de aplicaciones Shiny. Sin embargo, mejorar tu comprensión sobre ellos te ayudará a escribir aplicaciones correctas desde el principio. De este modo, cuando algo se comporte de manera inesperada, podrás concentrarte de manera más rápida en el problema subyacente. 
