# (PART\*) Mejores prácticas {.unnumbered}

# Introducción {#scaling-intro .unnumbered}

Cuando comienzas a utilizar Shiny, usualmente toma un tiempo largo hacer incluso aplicaciones pequeñas, ya que es necesario aprender los fundamentos. Sin embargo, con el paso del tiempo sentirás mayor comodidad con la interfaz básica de este paquete y con las ideas claves sobre reactividad. Esto te permitirá crear aplicaciones más largas y complejas. 

A medida que comiences a escribir aplicaciones más largas, encontrarás una nueva serie de desafíos: conservar de forma organizada, estable y mantenible una compleja y creciente base de código. Esto incluirá problemas como: 

-   "No puedo encontrar el código que estoy buscando en este archivo enorme."

-   "No he trabajado en este código en seis meses y temo romperlo si hago algún cambio."

-   "Alguien más empezó a trabajar conmigo en esta aplicación y constantemente nos estorbamos."

-   "La aplicación funciona en mi computador, pero no en el de mis colaboradores o en producción."

En esta parte del libro, enfocada en "mejores prácticas", aprenderás algunos conceptos clave y herramientas de ingeniería de software que te ayudarán a sobreponerte a algunos de estos desafíos. 

-   En el capítulo \@ref(best-practices), presentaré brevemente las grandes ideas de la ingeniería de software.

-   En el capítulo \@ref(scaling-functions), mostraré cómo extraer el código de tu aplicación Shiny hacia aplicaciones independientes y discutiremos por qué es algo que querrías hacer. 

-   En el capítulo \@ref(scaling-modules), aprenderás sobre el sistema de módulos de Shiny, que te permite extraer el código de una interfaz de usuario y de su servidor en componentes aislados y reutilizables.

-   En el capítulo \@ref(scaling-packaging), te mostraré cómo convertir tu aplicación en un paquete de R y explicaré por qué esta inversión vale la pena en el caso de aplicaciones más grandes. 

-   En el capítulo \@ref(scaling-testing), aprenderás a convertir los test informales que ya tienes en test automáticos que puedan ser fácilmente ejecutados cada vez que tu aplicación cambia. 

-   En el capítulo \@ref(performance), aprenderás a indentificar y resolver cuellos de botella en la performance de tus aplicaciones, para asegurarte que estas permanezcan rápidas incluso cuando son utilizadas por cientos de personas. 

Obviamente, no es posible aprender todo sobre ingeniería de software en una única parte de un libro, por lo que que también te sugiriré dónde puedes aprender más sobre el tema. 
