# https://atlas.oreilly.com/oreillymedia/mastering-shiny

library(fs)

# So we don't rebuild any demos
Sys.setenv(CI = "true")

# Build book --------------------------------------------------------------

# Clean out caches, figures, and previously built files
# TODO: move to temporary location so I can restore afterwards
dir_delete("_book")
dir_delete("_bookdown_files")

rmarkdown::render_site(
  output_format = rmarkdown::md_document(variant = "markdown"),
  quiet = TRUE
)

file_delete("_book/index.md")

# Copy figures  ----------------------------------------------------------------

# Figures generated by R code
files <- dir_ls("_bookdown_files", regexp = "_files$")
walk(files, dir_copy, "_book")

# Copy demos
dir_copy("demos", "_book")
rds <- dir_ls("_book/demos", recurse = T, glob = "*.rds")
file_delete(rds)

# Copy diagrams
dir_copy("diagrams", "_book")
graffle <- dir_ls("_book/diagrams", glob = "*.graffle")
file_delete(graffle)

# Copy screenshots
dir_copy("images", "_book")


# Alternative approach ---------------------------------------------------------
library(dplyr)

rmds <- dir_ls(glob = "*.Rmd")
names(rmds) <- rmds
resources <- purrr::map_df(rmds, rmarkdown::find_external_resources, .id = "rmd")
resources <- as_tibble(resources)

resources %>% filter(web) %>% pull(path)
