# (PART\*) Shiny in action {.unnumbered}

# Introduction {#action-intro .unnumbered}

The following chapters give you a grab bag of useful techniques.
I think everyone should start with Chapter \@ref(action-workflow), because it gives you important tools for developing and debugging apps, and getting help when you're stuck.

After that, there's no prescribed order and relatively few connections between the chapters: I'd suggest quickly skimming to get the lay of the land (and so you might remember these tools if related problems crop up in the future), and otherwise only deeply reading the bits that you currently need.
Here's a quick run down of the main topics:

-   Chapter \@ref(action-layout) details the various ways you can layout input and output components on a page, and how you can customise their appearance with themes.

-   Chapter \@ref(action-graphics) shows you how to add direct interaction to your plot and how to display images generated in other ways.

-   Chapter \@ref(action-feedback) covers a family of techniques (including inline errors, notifications, progress bars, and dialog boxes) for giving feedback to your users while you app runs.

-   Chapter \@ref(action-transfer) discusses how to transfer files to and from your app.

-   Chapter \@ref(action-dynamic) shows you how to dynamic modify your apps user interface while it runs.

-   Chapter \@ref(action-bookmark) shows how to record app state in such a way that your users can bookmark it.

-   Chapter \@ref(action-tidy) shows you how to allow users to select variables when working with tidyverse packages.

Let's begin by working on your workflow for developing apps.
